project:
  type: website
  output-dir: docs
  render:
    - /index.qmd
    - /advanced.qmd

website:
  title: "Shiny Express"
  navbar:
    search: true
    left:
      - text: "Basics"
        file: index.qmd
      - text: "Advanced topics"
        href: advanced.qmd
    right:
      - icon: github
        href: https://github.com/wch/shiny_express_doc

format:
  html:
    toc: true